name: ditto_sdk
description: Simple SDK to interact with Ditto and retrieve remote localizations.
version: 0.0.1+1
homepage: https://github.com/smsimone/ditto_sdk
publish_to: https://pub.dev

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  dotenv: ^4.0.1

flutter: null
