name: flutter_ditto
description: Simple library to interact with Ditto and retrieve remote localizations.
version: 1.0.0+2
homepage: https://github.com/smsimone/flutter-ditto.git

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hardcoded_strings: ^0.0.1
  http: ^0.13.4
  json_annotation: ^4.5.0
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.1.11
  custom_lint: ^0.1.1
  dotenv: ^4.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
