name: hardcoded_strings
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  analyzer: ^5.2.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.1.2-dev
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_test:
    sdk: flutter
