name: hardcoded_strings
description: Linter which notifies if the user is using hardcoded strings or invalid Ditto keys
version: 0.0.2+1
homepage: https://github.com/smsimone/flutter-ditto.git

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  analyzer: ^5.2.0
  analyzer_plugin: ^0.11.2
  args: ^2.3.1
  custom_lint_builder: ^0.1.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.5.0
  mutex: ^3.0.1
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
